---
- name: Configure Firewall
  hosts: ubuntu
  become: yes
  collections:
  - name: community.general
  tasks:
  - name: Setup firewall rule for SSH
    ufw:
      rule: limit
      name: OpenSSH
      state: enabled
...
