
---
- name: Configure Firewall
  hosts: ubuntu
  become: yes
  tasks: 
    - name: Setup firewall rule for SSH
      community.general.ufw:
        rule: limit
        name: OpenSSH
        state: enabled
...
