---
- name: Prepare Ubuntu
  hosts: ubuntu
  become: yes
  tasks: 
    - name: Install the packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        "{{ my_packages }}"
    - name: Check If zoom is installed
      command: dpkg-query -l 'zoom'
      register: zoom_check
      changed_when: false
    - name: Import Zoom Key
      rpm_key:
        key: https://zoom.us/linux/download/pubkey
        fingerprint: 3960 60CA DD8A 7522 0BFC B369 B903 BF18 61A7 C71D
        # Instructions on https://zoom.us/download?os=linux
    - name: Install Deb Zoom package from URL
      apt:
        deb: https://zoom.us/client/5.4.53391.1108/zoom_i386.deb
      when: zoom_check is failed
    - name: Update all packages to their latest version
      apt:
        name: "*"
        state: latest
...
